### ISSUE TITLE
Partially executed configurations if some build has failed.

### ISSUE THREAD

**Issue by taurus-forever** [jenkinsci/matrix-groovy-execution-strategy-plugin#11]
Hi,

I have configured matrix-groovy-execution-strategy-plugin like in examples and it does the job:

```
{
  x: [
    { axis1: "a", axis2: "x" },
    { axis1: "b", axis2: "x" }
  ],
  y: [
    { axis1: "a", axis2: "y" },
    { axis1: "b", axis2: "y" }
  ]
}
```

Unfortunately Jenkins doesn't execute section 'y' at all, if some build in section 'x' has failed.

Are there any ability to tell jenkins execute all available configurations and do not skip "y" if "x" has failed build?

P.S. UNSTABLE builds work as expected here, only FAILED aborts further building.

Thank you!

**Comment by JeremyMarshall** [comment]
Closed in favour of #12
