### ISSUE TITLE
Next axis execution stop if the previous axis fail

### ISSUE THREAD

**Issue by Biorix** [jenkinsci/matrix-groovy-execution-strategy-plugin#12]
Hi,
I use a groovy script to execute some configurations.
I used your example in order to do that : 
`
combinations.each{

    if (it.Model!='MatrixCircuit'){

            if (it.y== '1' && it.Scenario=='A' && env.y_A=='true'){
            result[it.y] = result[it.y] ?: []
            result[it.y] << it
            }
        else if (it.y== '1' && it.Scenario=='B' && env.y_B=='true'){
            result[it.y] = result[it.y] ?: []
            result[it.y] << it
            }
        }
    else{

        return
    }
}
result 

`
result is well defined and contain all the axis combinations I asked for. But if a 'major' axis execution fail, the following major axis are not executed.
How can I change this behavior ?

Thanks in advance

**Comment by JeremyMarshall** [comment]
Hi
currently it stops if it hits a failure.

I think I could make it return a tuple instead, the first being a result and the second a true/false of if to carry on after failure
```
(result, true|false)
```
or just the current behaviour where it will stop on error if there is no second value. This way you can configure the behaviour from a script

I'll investigate and get a version  released.

**Comment by taurus-forever** [comment]
Can you please share estimate date for the Jenkins plugin update including the fix here? Tnx!

**Comment by JeremyMarshall** [comment]
Hi

its fixed if you want to build it yourself. I'm having trouble getting the
tests working as I had to upgrade some of the internals to get it published
to the plugin library.

You can clone it then do `./gradlew jpi` to create it

what you need to do is `return [result, true]` at the end. I did it like
this so it doesn't break backwards compatibility - and you can decide in
the script if you want to continue after an error

**Comment by JeremyMarshall** [comment]
@taurus-forever I got it released - 1.0.6.

I'll update the wiki but what you need is to return an array
```
return [result, true] 
``` 
where the second element is whether you want to continue after a failure

The script can make the decision, which is why its here and not a check box, or something

If you just return the result then the behaviour is as before

**Comment by taurus-forever** [comment]
> I got it released - 1.0.6.

The fix has been confirmed. Thank you!
