### ISSUE TITLE
execution.getCurrentWorkspace() throws exception

### ISSUE THREAD

**Issue by qv-8942** [jenkinsci/matrix-groovy-execution-strategy-plugin#2]
I am configuring a matrix build for a multi platform project. Older branches use different toolchains. The information about the valid toolchains is stored in a file inside the project. I try to use your plugin, which seems to do what I need. The groovy script should read the toolchain file in order to choose a suitable build slave. The problem: 
`def filePath = execution.getCurrentWorkspace()`
results in
`groovy.lang.MissingMethodException: No signature of method: hudson.matrix.MatrixBuild$MatrixBuildExecution.getCurrentWorkspace() is applicable for argument types: () values: []`
This looks to me as if `execution` is a [MatrixBuild.MatrixBuildExecution](http://javadoc.jenkins-ci.org/hudson/matrix/MatrixBuild.MatrixBuildExecution.html), not a [OneOffExecutor](http://javadoc.jenkins-ci.org/hudson/model/OneOffExecutor.html).
I'm stuck... your help would be appreciated!
Adrian

**Comment by JeremyMarshall** [comment]
If you're after the workspace directory then this is available directly with `workspace` which is bound like `result` so you should be able to refer to in a script

```
println workspace
```

These are the bindings passed into the script

```
Map run( List<Combination> c) {

    Collections.shuffle(c)

    Binding binding = new Binding()
    binding.setVariable('jenkins', Jenkins.instance)
    binding.setVariable('combinations', c)
    binding.setVariable('workspace', this.workspace)
    binding.setVariable('execution', this.execution)
    binding.setVariable('result', new TreeMap<String, List<Combination>>())

    def res = script.evaluate(getClass().classLoader, binding)
    res
}
```

https://github.com/jenkinsci/matrix-groovy-execution-strategy-plugin/blob/master/src/main/groovy/org/jenkinsci/plugins/ScriptRunner.groovy

Please let me know if you need more information

**Comment by qv-8942** [comment]
Thank you!

Reading the file like this

```
String filePath = new String(workspace + "/path/to/file.txt")
toolchainstring = new File(fp).text
```

works well as long as the one-off executor runs on the master. If the one-off executor runs on a slave it seems that a FilePath object would be necessary to read the file. I am okay with that restriction.

I have got one open task left... The build is parameterized. One or more parameters should further restrict which configurations are built. Do you know a possibility to access the build parameters inside the script?

As workaround for not knowing how, I tried to use the Combination Filter. That worked im combination with the groofy script. But only with a hard-coded filter, I didn't succeed to access the build parameters from the filter.

Adrian

P.S. Is it somehow possible to write to the console from inside the script? println does not print anything.

**Comment by JeremyMarshall** [comment]
try this to get the parameters

```
import hudson.model.ParametersAction

def build = execution.build

def parameters = build?.actions.find{ it instanceof ParametersAction }?.parameters
parameters.each {
   println "parameter ${it.name}:"
   println it.dump()
}

def hardcoded_param = "aaa"
def resolver = build.buildVariableResolver
def hardcoded_param_value = resolver.resolve(hardcoded_param)
println "${hardcoded_param} = ${hardcoded_param_value}"

result
```

The first one prints all the parameters and the second gets the value of a parameter (called aaa in this case)

this is where I found some help http://stackoverflow.com/a/19564602/1213907

I'll find a better way to access the parameters, and the environment but I think this will work for now.

As to println - it does dump it to to the actual console if running Jenkins from the plugin but this does need to be improved and dump to the build output.

**Comment by qv-8942** [comment]
that did the trick. Thank you for helping me!

**Comment by JeremyMarshall** [comment]
I releases 1.0.4 which addresses your issues
There are now 3 new parameters passed into the script
parameters which is a hash of the build parameters
env which is a hash of the environment
out which sends the println output to the build log automatically

```
println '---------parameters--------'
parameters.each{ k,v ->
    println "${k}-->${v}"
}
println '-------------env--------------'
env.each{ k,v ->
    println "${k}-->${v}"
}
println '--------------------------------'
```

Please let me know how you get on 

Thanks
Jeremy
