### ISSUE TITLE
Example of matrix

### ISSUE THREAD

**Issue by ryf123** [jenkinsci/matrix-groovy-execution-strategy-plugin#3]
I am new to this, did not find any documentation specifying 
for example, if I want to run current project on node1 and node2 but not node3
what the matrix would look like?
matrix = [node1:"project_name", node2:"project_name"]  ?
could you point any documentation if any?

**Comment by JeremyMarshall** [comment]
Hi

The plugin only works with what is defined for the project. Its job is to filter out matrix combinations you don't want

So first of all you need to add an axis on of type node/label then select the ones you want. When the project is run then the plugin the plugin gets the list and filters it

Assuming your axis is called NODE

```
combinations.each {

    if(it.NODE == 'node3')
        return

    result[it.NODE] = result[it.NODE] ?: []
    result[it.NODE] << it
}

result
```

**Comment by ryf123** [comment]
Thanks @JeremyMarshall  I figured it out, my axis is called 'label', after I changed it to label, it works now
