### ISSUE TITLE
Weighted execution order

### ISSUE THREAD

**Issue by krsmith2** [jenkinsci/matrix-groovy-execution-strategy-plugin#4]
I use Jenkins to run my functional regression automation suites against our in-store point-of-sale system.  The test data is broken out into groups by store and each store's set of tests are run in parallel on up to 8 vms. If there are more stores than that, then the other stores have to wait on a vm to finish the store they are on.  I'm using matrix jobs to do this and wanted to have Jenkins start the store with the highest number of test scenarios first, followed by the second highest, and so on.  The goal is to have the "shorter" tests finish before the longest one, making better use of the environment and the time we have to run tests.
Currently Jenkins just starts the test in any order, so it may run the longest one first, maybe last, which means the next set of tests may have to wait longer than they would if the strategy started the longest running test first and then could recycle the VMs where the shorter tests all run.
I've been trying to get this to work using your plugin, but I can't seem to get it to order the output of the plugin correctly.

Say I have the following axis called 'StoreConfiguration' (the only other axis only has one value and is used to determine which set of VMs to run the tests on, so it doesn't matter).  The values is in the format "<Number of scenarios>-<Store Number>".

[1-6, 8-3, 4-12, 1-7, 1-33, 3-16]

For this case let's say I only have 4 VMs.  I need the tests to run in the following order (if the number of scenarios is the same, the store number order doesn't matter):

8-3, 4-12, 3-16, 1-33, 1-6, 1-7

But, I need them to run in parallel, so I can't use the transform that you have in the example because it will run 8-3, then 4-12, then 3-16, then 1-6, 1-7, & 1-33, waiting to run each set till the last set finishes.

Is it possible with your plugin to order the sets in parallel, or does it run each map item's list values randomly?

Thanks!

**Comment by JeremyMarshall** [comment]
Hi yes it is possible. what it will do is run the first set in parallel, when they are done move on to the second set, and so on.

You need to arrange to have your returned tree map look like this (assuming you want 3 at a time to run in parallel)

```
{
  a: [
    { StoreConfiguration: "8-3" },
    { StoreConfiguration: "4-12" },
    { StoreConfiguration: "3-16" },
  ],
  b: [
    { StoreConfiguration: "1-33" },
    { StoreConfiguration: "1-6" },
    { StoreConfiguration: "1-7" },
  ]
}
```

The order of the parallel set is alphabetical

**Comment by krsmith2** [comment]
Thanks Jeremy!

In your scenario, the way I understand it, the last 3 wouldn't run until the first 3 are _ALL_ complete.  Is that correct?  Unfortunately that isn't exactly what I'm needing.

I need any configuration in the second group to start as soon as any slave becomes available, so when 3-16 is done (it should be the first one of the top 3 to complete) then the next configuration in the ordered list should run on the available slave.

So, from what I'm seeing, this plugin probably won't work for what I need, I may have to write my own.

Again, thanks for the help!

**Comment by JeremyMarshall** [comment]
I see what you mean. You want them all in the queue but in your specific order. I need to check the code but I think it does execute the build in the order you place them in the queue. Certainly I randomise them before passing them into the user defined script. You could try fixing the order in 1 key. 

If you want to extend the plugin it is written in groovy using the gradle-jpi-plugin so needs ./gradlew server to test. I'm happy to take PRs if there are supporting tests

Jeremy

**Comment by krsmith2** [comment]
You're right, it does them in the order I put them in the map.

I've got it now!  :grinning: 

I just sort the collection first and then put them in the first map element (result[1]) in that order.

Thanks Jeremy!

**Comment by JeremyMarshall** [comment]
That's great! It's something I didn't consider at all. I'll update the wiki for that case

Regards

Jeremy
