### ISSUE TITLE
How to run jobs in parallel

### ISSUE THREAD

**Issue by ryf123** [jenkinsci/matrix-groovy-execution-strategy-plugin#5]
Hi Jeremy,

My result looks like this? and it runs in serial, the job on the second machine will only start after the job on the first machine finishes. do you know how to run the job on machines in parallel?

[sw-sd0201:[[label:sw-sd0201]], sw-sd0202:[[label:sw-sd0202]], sw-sd0206:[[label:sw-sd0206]], sw-sd0209:[[label:sw-sd0209]], sw-sd0210:[[label:sw-sd0210]], sw-sd0211:[[label:sw-sd0211]], sw-sd0212:[[label:sw-sd0212]], sw-sd0302:[[label:sw-sd0302]], sw-sd0311:[[label:sw-sd0311]], sw-sd0318:[[label:sw-sd0318]], bd0102:[[label:bd0102]], bd0103:[[label:bd0103]], bd0107:[[label:bd0107]], bd0108:[[label:bd0108]], bd0109:[[label:bd0109]], bd0110:[[label:bd0110]], it-sd0101:[[label:it-sd0101]], it-sd0103:[[label:it-sd0103]], it-sd0104:[[label:it-sd0104]], it-sd0105:[[label:it-sd0105]], it-sd0106:[[label:it-sd0106]], it-sd0107:[[label:it-sd0107]], it-sd0108:[[label:it-sd0108]], it-sd0110:[[label:it-sd0110]], it-sd0111:[[label:it-sd0111]], it-sd0112:[[label:it-sd0112]], it-sd0113:[[label:it-sd0113]], it-sd0114:[[label:it-sd0114]], it-sd0115:[[label:it-sd0115]]]

Thanks

**Comment by JeremyMarshall** [comment]
You can give this a try which will break the jobs into 4s and runs those 4 in parallel

```
def curr = 1
def cc = 0

combinations.each{

             def c = "${curr}"
             result[c] = result[c] ?: []
             result[c] << it

             if(cc > 3){
                 curr++
                 cc = 0
             }   
             cc++
}

println result.dump()

result
```

**Comment by ryf123** [comment]
thanks @JeremyMarshall ! 
this works
