### ISSUE TITLE
Adding a unique parameter per build configuration

### ISSUE THREAD

**Issue by nadarian** [jenkinsci/matrix-groovy-execution-strategy-plugin#8]
I am looking for a way to add to each build configuration a unique parameter like bundleID or hockeyappID. The groovy script doesn't let inject those parameters if they are not added as axes.

Say I have an {axis1:'a', axis2:'b'} this is a configuration I want to upload to with AppID abc123 and this configuration {axis1:'a', axis2:'c'} I want to upload with AppID xyz321. How can I achieve this?

**Comment by JeremyMarshall** [comment]
Not an issue with this plugin http://stackoverflow.com/questions/40424837/jenkins-build-matrix-with-unique-parameter-per-configuration/40446674#40446674
