### ISSUE TITLE
Disabling script approval for scripts on file system

### ISSUE THREAD

**Issue by martinmine** [jenkinsci/matrix-groovy-execution-strategy-plugin#9]
I have my Groovy script on a git repo that is checked out when my job runs and then executed through the groovy execution strategy plugin. Currently, I have to go on Jenkins and approve the script file every single time there is a change to it. Is there a way to disable this security check? I really don't want to go on Jenkins every single time and approve when there is a change to my script. The "approval" stage in my scenario is when I push to git.

**Comment by JeremyMarshall** [comment]
Hi
If its your Jenkins server you can give yourself admin script permissions. If it isn't then the whole script security concept is to restrict access. I raised this previously [google group](https://groups.google.com/forum/#!searchin/jenkinsci-dev/script$20security%7Csort:relevance/jenkinsci-dev/ktBfsN9Vn-o/ogCwV8-8m7QJ) about reading the file and approving ahead of time but any change will need revalidating

**Comment by pyleeric** [comment]
See http://blog.ehrnhoefer.com/2017-04-23-jenkins-groovy-security/ for some discussion and comments on this issue.

**Comment by lupalby** [comment]
It would be nice to add a checkbox to run the script in the groovy sandbox, so that the script approval can be skipped
